### PR TITLE
Add support for require() with CommonJS

### PR DESCRIPTION
**Pull request by PaulBGD**
Add supports to the JS version so we can use it with CommonJS.

### CODE REVIEW

**Comment by pradyunsg** [comment]
@PaulBGD Could you add a description?

**Comment by getify** [comment]
I think we should just have a separate branch for the AMD form of the lib, like we do for the node (CommonJS) form.

**Comment by pradyunsg** [comment]
Well, I think this is fine as it's a fairly trivial change. But I'm not really banking either way but would definitely prefer less branches.

**Comment by getify** [comment]
if we we're going to make this change, we should just change to the standard UMD wrapper and do away with having a separate node branch, since UMD works in AMD, CommonJS, and browser.

**Comment by pradyunsg** [comment]
Works by me. We'll probably need another node release though.

**Comment by getify** [comment]
+1

**Pull request closed without merging**
