### PR TITLE
Make this package installable for python

### PR DESCRIPTION
**Pull request by markriggins**
Handy package.  I like to use JSON files as config files, and thus like to be able to add comments.

Let's make this package installable so other python users can take advantage of it.

### CODE REVIEW

**Comment by markriggins** [comment]
I've decided to forego using it on my project in lieu of

return json.load(re.sub('//.*', '', file.read(), re.MULTILINE)

This removes all // characters to the end of line, but keeps the new-lines.
json.load then ignores the whitespace, and if it complains about the
format, then the line numbers actually correspond to those in the JSON file.

Simpler no?   Although, I can't have //'s in my variable content "a":"this
//might look like a comment"


Mark

**Comment by getify** [comment]
Yeah, if you are certain your values will never have `//` in them, AND if you don't want multi-line `/* .. */` support, AND if you're sure the source JSON is always on multiple lines and not already "minified" to a single line, the simplifying assumptions you've made are fine.

**Comment by markriggins** [comment]
Right.   Your solution is far more general and useful.

But I just wanted a few comments in a JSON file w/o picking up yet another
dependency.

Mark

**Comment by pradyun** [comment]
@markriggins Why not have an empty `__init__.py`?

**Comment by pradyunsg** [comment]
Closing as it is no longer valid post the repository re-organization.

**Pull request closed without merging**
