### PR TITLE
Perl version for JSON minify

### PR DESCRIPTION
**Pull request by rcoscali**
Hi !

Here is a pull request for the Perl port of JSON minify. 
Status:
Port is complete and all tests pass. The Perl modules is not yet finish but I can go on with it while merging in getify perl branch.
Once perl Module will be OK I'll post on CAPN (comprehensive perl archive network) and I'll update README to describe install from sources (repo) and from CPAN archives (distrib).

### CODE REVIEW

**Comment by rcoscali** [comment]
Sure doing it. It is automatically managed by GitKraken. I have a look at it by hand

**Comment by rcoscali** [comment]
Ok seems better this way.
Moved module to lib dir
Added a placeholder for a script command for using module (I'll write it this WE).
Perl module layout matching requirements for CPAN (v2.0)
I submit it once U merged


Best

**Comment by rcoscali** [comment]
Question: i didn't see any tests for the strip space mode ?
Is it wanted ? (some bug or any other reason)
I will add some

**Comment by rcoscali** [comment]
Could you have a look at the tests I added for !srip_space ?
If they are ok, you could move then in TESTING.md ?
The rendering of !strip_space is a little ugly. Perhaps we could achieve better rendering by tweaking a little bit his mode ? Not sure it is really useful... Or we could remove this mode ?

**Comment by rcoscali** [comment]
As soon as I have finished the command script I think it is ready to go

**Comment by lucasvazq** [comment]
F?

**Comment by lucasvazq** [comment]
> seems like either this .gitignore file could be completely removed, or at a minimum strip out a lot of that unnecessary stuff, especially the python stuff. no?

Approve it

https://github.com/getify/JSON.minify/pull/48/commits/4c37c140faef36342ef0fdad40ca9a49b2b0a12e

**Comment by rcoscali** [comment]
Rebased on 'base' branch.
Updated .gitignore for making dist files regexp more generic

**Review by getify — APPROVED** [review]

**Comment by getify** [comment]
I don't know much about Perl, but this looks reasonable to me. Thanks for sticking with this! Merging. :)

**Pull request merged**
