### PR TITLE
Fixed command and its test and doc tests 

### PR DESCRIPTION
**Pull request by rcoscali**

### CODE REVIEW

**Comment by getify** [comment]
I don't know hardly anything about python so I don't have any context as to why these changes are being submitted. Thus I cannot review it to see if they're appropriate.

**Comment by rcoscali** [comment]
This is perl not python :) !
Actually I'm adding CI/CD and you will be able to check test results/artifacts for having a good idea of quality.
The JSON_minify perl module is published on CPAN and this is also some indication on quality.
However, decision is yours ;-) 
Let me time for terminating the github actions setup and in a few hours I'll ping you and you'll be able to have a look at results.
Have a good day !

Regards

**Comment by rcoscali** [comment]
A little more context:
A perl module is distributed on CPAN (cpan.org: comprehensive perl archive network). Such an artifact is distributed with its own tests and documentation (and doc tests). While rebuilding it I saw a few tests where actually missing from the manifest and a few dependencies where missing for doc tests. At the origin I planned to add a test for the no-strip option and for the command (json_minify.pl). These were not listed in MANIFEST file.

**Comment by getify** [comment]
> This is perl not python :) !

Sorry, I misread ".pl" and ".py" on my phone. :)

**Comment by getify** [comment]
My main concern was that this PR was submitted without any text in the main OP. That's often a warning sign of spam or whatever.

I appreciate your apparently diligent efforts and have no reason to doubt the quality. I just didn't understand what an empty-text PR was expecting. I would still appreciate, either in the OP message, or here in this comment thread, some basic descriptions (bullet list) of what's being affected by the PR. You mention "missing tests", which is helpful, but I would appreciate, if only for posterity sake, a little more detail. :)

**Comment by rcoscali** [comment]
Sure! Sorry for it. I'll take care of this for the next ones  ... :)
I also added some actions for CI CD you could use as template for other branches if you want. Still a few command to check on the dist action for checking that the dist is actually correctly posted to cpan.org (a warning for releasing the last module to the perl community)!!

You can now check and commit I think so then enjoy seeing actions going to green :)
(see https://github.com/rcoscali/JSON.minify/actions for runs)

Best regards

**Comment by rcoscali** [comment]
I'll eventually try to create & post some artifacts (dist file released) in a wiki page for the perl branch (as it is done for many other projects on github). For a language having a package manager this is not so usefull but it could be used as a template for your other languages, and also eventuelly have a meta release page with all dist aggregated -- why not, not sure it is usefull ;-)

See you !

PS: I'll create a PR for it ...

**Comment by getify** [comment]
is this PR ready to consider for merging, or are you still making more changes?

**Comment by rcoscali** [comment]
Yes this is ready for merging. 
I'll make more changes later in another PR where I'll describe the missing artifacts and need to post releases in a wiki page.
I'll also create another one for checking delta with cpan...
But these are entire new stories ... :)

**Pull request merged**
